from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    database_url: str = "postgresql+psycopg://fleet:fleet@localhost:5432/fleet"

    # Database schema management
    # For production: set db_auto_create_tables=false and run `alembic upgrade head` during deploy.
    db_auto_create_tables: bool = True
    db_require_migrations_up_to_date: bool = True

    # Admin endpoints
    admin_enable_migrations_endpoint: bool = False

    # Agent long-poll and online heuristics
    agent_poll_timeout_seconds: int = 25
    agent_online_grace_seconds: int = 10

    # Agent authentication (shared secret MVP)
    # By default, the server requires a shared token for all /agent/* endpoints.
    # Set AGENT_SHARED_TOKEN (recommended) or explicitly allow insecure dev mode.
    agent_shared_token: str | None = None
    allow_insecure_no_agent_token: bool = False

    # Ansible integration
    ansible_dir: str = "ansible"
    ansible_log_dir: str = "ansible/logs"
    ansible_store_output_max_chars: int = 20000

    # Ansible SSH defaults (used by in-app Ansible runner)
    ansible_ssh_user: str = "ubuntu"
    ansible_private_key_file: str | None = None  # e.g. /root/.ssh/id_ed25519

    # UI auth
    ui_cookie_secure: bool = False  # set True behind HTTPS
    ui_session_days: int = 30
    # If true, revoke all UI sessions on server startup (useful when you want restart=>forced relogin).
    ui_revoke_all_sessions_on_startup: bool = False

    # MFA (TOTP)
    # Required for admin/operator when mfa_require_for_privileged=true
    mfa_require_for_privileged: bool = True
    mfa_totp_issuer: str = "linux-central-management"
    # 32-byte urlsafe base64 key for Fernet (e.g. generated by `python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())'`)
    mfa_encryption_key: str | None = None

    # CORS (for separate-origin frontend)
    # Comma-separated list via env is supported by pydantic-settings for list fields.
    cors_allow_origins: list[str] = []  # e.g. ["https://ui.example.com"]
    cors_allow_origin_regex: str | None = None
    cors_allow_headers: list[str] = ["*"]
    cors_allow_methods: list[str] = ["*"]
    cors_allow_credentials: bool = True

    # Bootstrap UI user (only used if the user doesn't exist yet)
    # SECURITY: do NOT ship a default password; require env override on first run.
    bootstrap_username: str = "admin"
    bootstrap_password: str | None = None

    # Terminal proxy to agent (high-risk feature)
    agent_terminal_scheme: str = "ws"  # ws|wss
    agent_terminal_port: int = 18080
    agent_terminal_token: str | None = None  # must match agent-side token

    # Security headers (recommended if exposed beyond LAN)
    security_headers_enabled: bool = True
    # Optional Content-Security-Policy override. If unset, app_factory applies a nonce-based default policy.
    content_security_policy: str | None = None

    # Background metrics refresh (for fast Overview/Attention updates)
    metrics_background_refresh_seconds: int = 60  # set 0 to disable
    metrics_background_batch_limit: int = 50

    # Teams notifications
    teams_webhook_url: str | None = None
    teams_alerts_enabled: bool = False

    # Notification center backend dedupe/cooldown
    notifications_dedupe_enabled: bool = True
    # Cooldown window for the same notification key (kind+host/action), in seconds.
    notifications_dedupe_cooldown_seconds: int = 1800

    # Maintenance windows (guardrails for risky actions)
    maintenance_window_enabled: bool = False
    maintenance_window_timezone: str = "UTC"
    maintenance_window_start_hhmm: str = "01:00"
    maintenance_window_end_hhmm: str = "05:00"
    # CSV list of guarded actions, e.g. "dist-upgrade,security-campaign"
    maintenance_window_guarded_actions: str = "dist-upgrade,security-campaign"

    # Two-person approval for high-risk actions
    high_risk_approval_enabled: bool = False
    # CSV list, e.g. "dist-upgrade,security-campaign"
    high_risk_approval_actions: str = "dist-upgrade,security-campaign"

    # OIDC SSO (week-1 foundation)
    auth_oidc_enabled: bool = False
    auth_oidc_issuer: str | None = None
    auth_oidc_client_id: str | None = None
    auth_oidc_client_secret: str | None = None
    auth_oidc_redirect_uri: str | None = None
    auth_oidc_scopes: str = "openid profile email"
    auth_oidc_allowed_email_domains: str | None = None
    # JSON object map: {"oidc-group-name":"role"}, role in admin|operator|readonly
    auth_oidc_group_role_map: str | None = None
    # JSON object map for scope sync by group.
    # Example: {"fleet-prod":[{"env":["prod"]}],"fleet-core":{"team":["core"]}}
    auth_oidc_group_scope_map: str | None = None


settings = Settings()
