#!/usr/bin/env python3
"""Generate the server and agent version constants from the root VERSION file."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys


REPO_ROOT = Path(__file__).resolve().parents[1]
NUMERIC_IDENTIFIER = r"(?:0|[1-9][0-9]*)"
PRERELEASE_IDENTIFIER = rf"(?:{NUMERIC_IDENTIFIER}|[0-9]*[A-Za-z-][0-9A-Za-z-]*)"
SEMVER = re.compile(
    rf"{NUMERIC_IDENTIFIER}\.{NUMERIC_IDENTIFIER}\.{NUMERIC_IDENTIFIER}"
    rf"(?:-{PRERELEASE_IDENTIFIER}(?:\.{PRERELEASE_IDENTIFIER})*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?"
)


def generated_files(version: str) -> dict[str, str]:
    return {
        "server/app/version.py": (
            "# Generated by scripts/sync-version.py from VERSION; do not edit.\n"
            f'APP_VERSION = "{version}"\n'
        ),
        "agent/cmd/fleet-agent/version.go": (
            "// Code generated by scripts/sync-version.py from VERSION; DO NOT EDIT.\n"
            "\npackage main\n\n"
            f'const AgentVersion = "{version}"\n'
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report missing or outdated generated files without changing them",
    )
    args = parser.parse_args()

    try:
        version = (REPO_ROOT / "VERSION").read_text(encoding="utf-8").strip()
        if not SEMVER.fullmatch(version):
            raise ValueError("VERSION must contain a valid SemVer, for example 0.1.0-beta.1")

        stale = []
        for relative_path, expected in generated_files(version).items():
            path = REPO_ROOT / relative_path
            actual = path.read_text(encoding="utf-8") if path.exists() else None
            if actual == expected:
                continue
            stale.append(relative_path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(expected, encoding="utf-8")
                print(f"Updated {relative_path}")

        if args.check and stale:
            for relative_path in stale:
                print(f"Missing or outdated: {relative_path}", file=sys.stderr)
            print("Run python3 scripts/sync-version.py", file=sys.stderr)
            return 1
    except (OSError, UnicodeError, ValueError) as exc:
        print(f"Version sync failed: {exc}", file=sys.stderr)
        return 2

    print(f"Version files are up to date ({version}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
